### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ar664** [IGuessThisIsMyLife/project2-graphs#1]
I will be doing the code review with this issue. Please don't close it until the semester is over thank you.

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/GridGraph.py#L22
I would recommend putting making this statement a boolean variable like `isNeighbor` for better readability.

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/GridGraph.py#L23-L24
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/GridGraph.py#L30-L31
Might want to have parenthesis between the `and` operator to better distinguish the two expressions.

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/TopSort.py#L14-L16
Small nitpick, I like to keep my variable declarations close together, unless I am initializing them.

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L24
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L31
This is a strange way to keep track of the weights. I would suggest either keeping it like you did the adjacency list (seen below) or using some other metric to determine the value of the key in a dictionary like a tuple.
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L23

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L23
I think calling min and max, to refer to index 0 and 1 is a bit excessive. You could just do [0] and [1] if I am not mistaken.

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L57-L60
I am not sure why you commented out Dijkstra's, If you need help, feel free to DM me. Small nit pick, but dijkstras should be spelled djikstras.

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L81-L91
Good choice doing both the adding of grid nodes and edges at the same time. However, I am uncertain if this is faster than adding nodes first, and then doing connections. Because you could do connections in O(n) time by iterating through each node and getting their neighbors and iterating through them, which would reduce the work I am assuming.

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L13
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L29
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L44
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L78
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L102-L105
One letter variables that aren't self explanatory should be avoided. X is good because it describes the x position, but g is not because it is not a standard reference for graph. So you should not be afraid to make the variables a little bigger for readability.

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/part_1.py#L151-L155
May not want to use a while True statement, as it could result in unhalted code. A possible remedy is keeping a counter of connections, and doing
```python
while counter < maxConnections:
```

**Comment by ar664** [comment]
https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/part_1.py#L188
I think you fixed this in you newest part 2, so I am just going to say go over this old part to match with the current way you are doing things.

**Comment by ar664** [comment]
I can see that some of your code is incomplete, but what you have so far is promising. Keep working and I think you should be good. Have a good semester! 😀

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L24
> 
> 
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L31
> 
> 
> This is a strange way to keep track of the weights. I would suggest either keeping it like you did the adjacency list (seen below) or using some other metric to determine the value of the key in a dictionary like a tuple.
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L23

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L24
> 
> 
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L31
> 
> 
> This is a strange way to keep track of the weights. I would suggest either keeping it like you did the adjacency list (seen below) or using some other metric to determine the value of the key in a dictionary like a tuple.
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/WeightedGraph.py#L23

So I used this format because i'm taking advantage of the dictionary's ability to use anything as a key reference and I did this because it made the most sense to me when regarding directed edges, since just because node a points to b doesnt mean b points to a.  I understand what you're saying, but this specifically was my preference.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/part_1.py#L151-L155
> 
> 
> May not want to use a while True statement, as it could result in unhalted code. A possible remedy is keeping a counter of connections, and doing
> ```python
> while counter < maxConnections:
> ```

The reason I have it working like this is because random is involved and I can't control which two get sampled so I have a while True to make sure it create the proper edges.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/part_1.py#L188
> 
> 
> I think you fixed this in you newest part 2, so I am just going to say go over this old part to match with the current way you are doing things.

I modified my old file to match the way I do things now.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L23
> 
> 
> I think calling min and max, to refer to index 0 and 1 is a bit excessive. You could just do [0] and [1] if I am not mistaken.

I had done it like this for the sole purpose of not having cycles. If the direction is always from the minimum to the max, there will never be a cycle.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L57-L60
> 
> 
> I am not sure why you commented out Dijkstra's, If you need help, feel free to DM me. Small nit pick, but dijkstras should be spelled djikstras.

It was commented out because it didnt work, but im replacing it with a TODO. Also i looked it up and it's spelled Dijkstra's.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L81-L91
> 
> 
> Good choice doing both the adding of grid nodes and edges at the same time. However, I am uncertain if this is faster than adding nodes first, and then doing connections. Because you could do connections in O(n) time by iterating through each node and getting their neighbors and iterating through them, which would reduce the work I am assuming.

The way I have things set up made this way easier, so I think i'll stick with what I have for now, but thank you for the advice.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L13
> 
> 
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L29
> 
> 
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L44
> 
> 
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L78
> 
> 
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/main.py#L102-L105
> 
> 
> One letter variables that aren't self explanatory should be avoided. X is good because it describes the x position, but g is not because it is not a standard reference for graph. So you should not be afraid to make the variables a little bigger for readability.

I changed all my single letter variables that weren't descriptive enough.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/TopSort.py#L14-L16
> 
> 
> Small nitpick, I like to keep my variable declarations close together, unless I am initializing them.

I fixed this spacing issue.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/GridGraph.py#L22
> 
> 
> I would recommend putting making this statement a boolean variable like `isNeighbor` for better readability.

Other comments pointed out this statement also just doesnt work so im going to follow what they say, but thank you for the advice.

**Comment by IGuessThisIsMyLife** [comment]
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/GridGraph.py#L23-L24
> 
> 
> https://github.com/IGuessThisIsMyLife/project2-graphs/blob/b423b1749bb1213958b7d930d78ff79348dd4721/GridGraph.py#L30-L31
> 
> 
> Might want to have parenthesis between the `and` operator to better distinguish the two expressions.

I was told in other comments i acutally dont need the second expression if I did this correctly so Im removing the second expression altogether, but thank you for the advice.

**Comment by IGuessThisIsMyLife** [comment]
Addressed comments here - https://github.com/IGuessThisIsMyLife/project2-graphs/tree/master/project2%20revised
